name: arch_dart
description: Dart/Flutter Architectural Testing Framework inspired by ArchUnit for Java.
version: 0.0.1
homepage: https://github.com/evandersondev/arch_dart
license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  analyzer: ^7.5.4
  path: ^1.9.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
